from ALU_simulator.Test.Comparators.TestIsEqual0 import TestIsEqual0
from ALU_simulator.Test.Comparators.TestBitExtend1to32 import TestBitExtend1to32
from ALU_simulator.Test.Comparators.TestIsEqual import TestIsEqual
from ALU_simulator.Test.Comparators.TestMSB import TestMSB
from ALU_simulator.Test.Comparators.TestLessThanOrEqual0 import TestLessThanOrEqual0